# Generated by Django 5.1.6 on 2025-03-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=50)),
                ('kategori', models.CharField(choices=[('Teknoloji', 'Teknoloji'), ('Spor', 'Spor'), ('Ekonomi', 'Ekonomi'), ('Magazin', 'Magazin')], max_length=20)),
                ('yayinTarihi', models.DateTimeField(auto_now_add=True)),
                ('yazar', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
