# Generated by Django 5.1.6 on 2025-03-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='icerik',
            field=models.TextField(default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='haber',
            name='baslik',
            field=models.CharField(default='', max_length=50),
        ),
    ]
