# Generated by Django 5.1.6 on 2025-04-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_haber_icerik_alter_haber_baslik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haber',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='haber',
            name='yayinTarihi',
        ),
        migrations.RemoveField(
            model_name='haber',
            name='yazar',
        ),
        migrations.AlterField(
            model_name='haber',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='haber',
            name='icerik',
            field=models.TextField(),
        ),
    ]
