# Generated by Django 5.1.4 on 2025-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0003_remove_haber_kategori_remove_haber_yayintarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='baslik',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='haber',
            name='icerik',
            field=models.TextField(default='', max_length=155),
        ),
    ]
