# Generated by Django 5.1.6 on 2025-04-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='content',
            field=models.TextField(default='Henüz içerik girilmedi.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitap',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='kitap',
            name='published_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
